
name: Zip Files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: 3d_monolayer/
          dest: 3d_monolayer_tutorial_files.zip
      - uses: actions/upload-artifact@v1
        with:
          name: 3d_monolayer_tutorial_files
          path: ${{ github.workspace }}/3d_monolayer_tutorial_files.zip
